name: geosardine
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - numpy>=1.18
  - gdal>=3.0.4
  - rasterio>=1.1.2
  - fiona>=1.8.13
  - affine>=2.3.0
  - shapely>=1.6.4
  - tqdm>=4.48.2
  - numba>=0.51.2