{% set name = "geosardine" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7acbe0fc354c668e972cdcff4ed32b6ecd47fa65632606c9499f3a14a9dcdb4

build:
  noarch: python
  number: 0
  entry_points:
    - dine = geosardine.__main__:main
#  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - pytest-runner
#    - poetry

  run:
    - affine >=2.3.0,<3.0.0
    - click >=7.1.2,<8.0.0
    - fiona >=1.8.13,<2.0.0
    - gdal >=3.0.4,<4.0.0
    - numba >=0.51.2,<0.52.0
    - numpy >=1.18,<2.0
    - python >=3.6,<4.0
    - rasterio >=1.1.4,<2.0.0
    - shapely >=1.6.4,<2.0.0
    - tqdm


test:
  imports:
    - geosardine
    - geosardine.interpolate
  commands:
    - pip check
    - dine --help
  requires:
    - pytest

about:
  home: https://github.com/sahitono/geosardine
  summary: Spatial operations extend fiona and rasterio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sahitono
