{% set name = "geosardine" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb0a47b7b75d933e0c784b95e2d607ffa3f3d532193aa7b679dd5633b7e3c5b5

build:
  noarch: python
  number: 0
  entry_points:
    - dine = geosardine.__main__:main
#  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - pytest-runner
#    - poetry

  run:
    - affine >=2.3.0,<3.0.0
    - click >=7.1.2,<8.0.0
    - fiona >=1.8.13,<2.0.0
    - gdal >=3.0.4,<3.1.4
    - numba >=0.51.2,<0.52.0
    - numpy >=1.18,<2.0
    - python >=3.6,<4.0
    - rasterio >=1.1.4,<2.0.0
    - shapely >=1.6.4,<2.0.0
    - tqdm
    - opencv >=4.4.0,<5.0.0


test:
  imports:
    - geosardine
    - geosardine.interpolate
    - geosardine.raster
  commands:
    - dine --help
  requires:
    - pytest

about:
  home: https://github.com/sahitono/geosardine
  summary: Spatial operations extend fiona and rasterio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sahitono
